# Copyright (c) 2026, Oracle and/or its affiliates.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2.0,
# as published by the Free Software Foundation.

# Configure optional MySQL Vector native backend dependencies.
MACRO(MYSQL_VECTOR_CONFIGURE_APPLE_OPENMP)
  IF(APPLE)
    FIND_PATH(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR
      NAMES omp.h
      PATHS
        /opt/homebrew/opt/libomp/include
    )
    FIND_LIBRARY(MYSQL_VECTOR_LIBOMP_LIBRARY
      NAMES omp libomp
      PATHS
        /opt/homebrew/opt/libomp/lib
    )
    IF(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR AND MYSQL_VECTOR_LIBOMP_LIBRARY)
      SET(OpenMP_C_FLAGS "-Xpreprocessor -fopenmp" CACHE STRING
          "OpenMP C flags for vector source builds" FORCE)
      SET(OpenMP_CXX_FLAGS "-Xpreprocessor -fopenmp" CACHE STRING
          "OpenMP CXX flags for vector source builds" FORCE)
      SET(OpenMP_C_INCLUDE_DIR "${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR}" CACHE PATH
          "OpenMP C include dir for vector source builds" FORCE)
      SET(OpenMP_CXX_INCLUDE_DIR "${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR}" CACHE PATH
          "OpenMP CXX include dir for vector source builds" FORCE)
      SET(OpenMP_C_LIB_NAMES "omp" CACHE STRING
          "OpenMP C libraries for vector source builds" FORCE)
      SET(OpenMP_CXX_LIB_NAMES "omp" CACHE STRING
          "OpenMP CXX libraries for vector source builds" FORCE)
      SET(OpenMP_omp_LIBRARY "${MYSQL_VECTOR_LIBOMP_LIBRARY}" CACHE FILEPATH
          "OpenMP runtime library for vector source builds" FORCE)
    ENDIF()
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_FAIL_LEGACY_OPTION legacy_option replacement_option)
  IF((DEFINED ${legacy_option} AND NOT "${${legacy_option}}" STREQUAL "") OR
     NOT "$ENV{${legacy_option}}" STREQUAL "")
    MESSAGE(FATAL_ERROR
      "${legacy_option} is no longer supported by MySQL Vector. "
      "Use ${replacement_option} instead.")
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_CACHE_PATH_HINT option_name doc_string)
  SET(${option_name} "" CACHE PATH "${doc_string}")
  SET(${option_name}_HINTS "${${option_name}}")
  IF(NOT ${option_name}_HINTS)
    SET(${option_name}_HINTS "$ENV{${option_name}}")
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_CACHE_BOOL_HINT option_name doc_string default_value)
  IF(NOT DEFINED ${option_name} AND NOT "$ENV{${option_name}}" STREQUAL "")
    SET(${option_name} "$ENV{${option_name}}" CACHE BOOL "${doc_string}" FORCE)
  ELSE()
    OPTION(${option_name} "${doc_string}" ${default_value})
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_SET_FIND_LIBRARY_MODE static_option)
  SET(MYSQL_VECTOR_SAVED_FIND_LIBRARY_SUFFIXES
      "${CMAKE_FIND_LIBRARY_SUFFIXES}")
  IF(${static_option})
    SET(CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_STATIC_LIBRARY_SUFFIX}")
  ELSE()
    SET(CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_SHARED_LIBRARY_SUFFIX}")
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_RESTORE_FIND_LIBRARY_MODE)
  SET(CMAKE_FIND_LIBRARY_SUFFIXES
      "${MYSQL_VECTOR_SAVED_FIND_LIBRARY_SUFFIXES}")
  UNSET(MYSQL_VECTOR_SAVED_FIND_LIBRARY_SUFFIXES)
ENDMACRO()

MACRO(MYSQL_VECTOR_CONFIGURE_BACKENDS)
  SET(FAISS_TARGET "")
  SET(HNSWLIB_TARGET "")
  SET(MYSQL_VECTOR_DISKANN_OFFLINE_TARGET "")
  SET(MYSQL_VECTOR_DISKANN_VENDORED_TARGET "")

  IF(HAVE_VECTOR_INDEX)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_FAISS_INCLUDE_DIR
                                    MYSQL_VECTOR_FAISS_INCLUDES)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_FAISS_LIBRARY_DIR
                                    MYSQL_VECTOR_FAISS_LIB_DIR)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_HNSWLIB_INCLUDE_DIR
                                    MYSQL_VECTOR_HNSWLIB_INCLUDES)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_LIB
                                    MYSQL_VECTOR_DISKANN_LIB_DIR)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_OFFLINE_LIB
                                    "MYSQL_VECTOR_DISKANN_ROOT or MYSQL_VECTOR_DISKANN_LIB_DIR")
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_OFFLINE_LIB_DIR
                                    "MYSQL_VECTOR_DISKANN_ROOT or MYSQL_VECTOR_DISKANN_LIB_DIR")
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_INCLUDE_DIR
                                    MYSQL_VECTOR_DISKANN_INCLUDES)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_INCLUDES
                                    MYSQL_VECTOR_DISKANN_INCLUDES)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_BUILD_DIR
                                    "MYSQL_VECTOR_DISKANN_ROOT or MYSQL_VECTOR_DISKANN_LIB_DIR")
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_LIBRARY
                                    MYSQL_VECTOR_DISKANN_LIB_DIR)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_LIB_DIR
                                    MYSQL_VECTOR_DISKANN_LIB_DIR)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_STATIC
                                    MYSQL_VECTOR_DISKANN_STATIC)
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_EXTRA_LIBS
                                    "system library search paths")
    MYSQL_VECTOR_FAIL_LEGACY_OPTION(MYSQL_VECTOR_DISKANN_CPP_CMAKE_ARGS
                                    MYSQL_VECTOR_DISKANN_ROOT)
    MYSQL_VECTOR_CACHE_BOOL_HINT(MYSQL_VECTOR_FAISS
      "Enable the Faiss vector backend" ON)
    MYSQL_VECTOR_CACHE_BOOL_HINT(MYSQL_VECTOR_HNSW
      "Enable the hnswlib vector backend" ON)
    MYSQL_VECTOR_CACHE_BOOL_HINT(MYSQL_VECTOR_DISKANN
      "Enable the DiskANN vector backend" ON)
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_FAISS_ROOT
      "Root directory of the Faiss source tree or installation")
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_FAISS_INCLUDES
      "Directory containing Faiss headers")
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_FAISS_LIB_DIR
      "Directory containing the Faiss library")
    MYSQL_VECTOR_CACHE_BOOL_HINT(MYSQL_VECTOR_FAISS_STATIC
      "Prefer a static Faiss library when using MYSQL_VECTOR_FAISS_LIB_DIR" OFF)
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_HNSWLIB_ROOT
      "Root directory of the hnswlib source tree or installation")
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_HNSWLIB_INCLUDES
      "Directory containing hnswlib headers")
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_DISKANN_ROOT
      "Root directory of the official DiskANN source tree")
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_DISKANN_INCLUDES
      "Directory containing official DiskANN C++ public headers")
    MYSQL_VECTOR_CACHE_PATH_HINT(MYSQL_VECTOR_DISKANN_LIB_DIR
      "Directory containing official DiskANN libraries")
    MYSQL_VECTOR_CACHE_BOOL_HINT(MYSQL_VECTOR_DISKANN_STATIC
      "Prefer static DiskANN libraries from MYSQL_VECTOR_DISKANN_LIB_DIR" OFF)
    OPTION(MYSQL_VECTOR_ENABLE_NATIVE_SIMD
           "Compile native vector backends with CPU-native SIMD flags when available"
           ON)
    SET(MYSQL_VECTOR_FAISS_OPT_LEVEL "" CACHE STRING
        "Faiss source-build CPU SIMD optimization level; empty selects the MySQL default")
    SET_PROPERTY(CACHE MYSQL_VECTOR_FAISS_OPT_LEVEL PROPERTY STRINGS
                 "" generic dd avx2 avx512 avx512_spr sve)

    IF(NOT MYSQL_VECTOR_FAISS)
      SET(MYSQL_VECTOR_FAISS_ROOT_HINTS "")
      SET(MYSQL_VECTOR_FAISS_INCLUDES_HINTS "")
      SET(MYSQL_VECTOR_FAISS_LIB_DIR_HINTS "")
    ENDIF()
    IF(NOT MYSQL_VECTOR_HNSW)
      SET(MYSQL_VECTOR_HNSWLIB_ROOT_HINTS "")
      SET(MYSQL_VECTOR_HNSWLIB_INCLUDES_HINTS "")
    ENDIF()
    IF(NOT MYSQL_VECTOR_DISKANN)
      SET(MYSQL_VECTOR_DISKANN_ROOT_HINTS "")
      SET(MYSQL_VECTOR_DISKANN_INCLUDES_HINTS "")
      SET(MYSQL_VECTOR_DISKANN_LIB_DIR_HINTS "")
    ENDIF()
    SET(MYSQL_VECTOR_DISKANN_LIB_HINT "")
    SET(MYSQL_VECTOR_FAISS_INCLUDE_HINTS
        "${MYSQL_VECTOR_FAISS_INCLUDES_HINTS}")
    SET(MYSQL_VECTOR_FAISS_LIBRARY_HINTS
        "${MYSQL_VECTOR_FAISS_LIB_DIR_HINTS}")
    SET(MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS
        "${MYSQL_VECTOR_HNSWLIB_INCLUDES_HINTS}")
    SET(MYSQL_VECTOR_DISKANN_ROOT_HINT
        "${MYSQL_VECTOR_DISKANN_ROOT_HINTS}")
    SET(MYSQL_VECTOR_DISKANN_INCLUDE_HINTS
        "${MYSQL_VECTOR_DISKANN_INCLUDES_HINTS}")
    SET(MYSQL_VECTOR_DISKANN_LIB_DIR_HINT
        "${MYSQL_VECTOR_DISKANN_LIB_DIR_HINTS}")
    SET(MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT "")
    UNSET(FAISS_INCLUDE_DIR CACHE)
    UNSET(FAISS_LIBRARY CACHE)
    UNSET(HNSWLIB_INCLUDE_DIR CACHE)

    SET(FAISS_TARGET "")
    SET(MYSQL_VECTOR_FAISS_TARGET_INCLUDE_ROOT "")
    IF(MYSQL_VECTOR_FAISS_ROOT_HINTS AND
       EXISTS "${MYSQL_VECTOR_FAISS_ROOT_HINTS}/CMakeLists.txt" AND
       EXISTS "${MYSQL_VECTOR_FAISS_ROOT_HINTS}/faiss/Index.h")
      MYSQL_VECTOR_CONFIGURE_APPLE_OPENMP()

      SET(MYSQL_VECTOR_FAISS_SAVED_BUILD_TESTING "${BUILD_TESTING}")
      SET(MYSQL_VECTOR_FAISS_RESTORE_BUILD_TESTING FALSE)
      IF(DEFINED BUILD_TESTING)
        SET(MYSQL_VECTOR_FAISS_RESTORE_BUILD_TESTING TRUE)
      ENDIF()

      SET(BUILD_TESTING OFF CACHE BOOL "Disable Faiss tests in MySQL builds" FORCE)
      SET(FAISS_ENABLE_GPU OFF CACHE BOOL "Disable Faiss GPU support in MySQL builds" FORCE)
      SET(FAISS_ENABLE_CUVS OFF CACHE BOOL "Disable Faiss cuVS support in MySQL builds" FORCE)
      SET(FAISS_ENABLE_ROCM OFF CACHE BOOL "Disable Faiss ROCm support in MySQL builds" FORCE)
      SET(FAISS_ENABLE_MKL OFF CACHE BOOL "Disable Faiss MKL in MySQL builds" FORCE)
      SET(FAISS_ENABLE_PYTHON OFF CACHE BOOL "Disable Faiss Python bindings in MySQL builds" FORCE)
      SET(FAISS_ENABLE_C_API OFF CACHE BOOL "Disable Faiss C API in MySQL builds" FORCE)
      SET(FAISS_ENABLE_EXTRAS OFF CACHE BOOL "Disable Faiss demos and extras in MySQL builds" FORCE)
      SET(FAISS_ENABLE_SVS OFF CACHE BOOL "Disable Faiss SVS integration in MySQL builds" FORCE)
      SET(FAISS_USE_LTO OFF CACHE BOOL "Disable Faiss LTO in MySQL builds" FORCE)
      IF(MYSQL_VECTOR_FAISS_STATIC AND
         NOT (MYSQL_VECTOR_DISKANN AND MYSQL_VECTOR_DISKANN_STATIC))
        SET(BLA_STATIC ON CACHE BOOL
            "Prefer static BLAS/LAPACK libraries for vector Faiss builds" FORCE)
        UNSET(BLAS_openblas_LIBRARY CACHE)
        UNSET(LAPACK_openblas_LIBRARY CACHE)
      ENDIF()
      IF(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND "${BLA_VENDOR}" STREQUAL "")
        SET(BLA_VENDOR "OpenBLAS" CACHE STRING
            "Prefer OpenBLAS for Faiss source builds when MKL is disabled" FORCE)
      ENDIF()
      SET(MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL
          "${MYSQL_VECTOR_FAISS_OPT_LEVEL}")
      IF(NOT MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL)
        IF(MYSQL_VECTOR_ENABLE_NATIVE_SIMD AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
          SET(MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL "dd")
        ELSE()
          SET(MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL "generic")
        ENDIF()
      ENDIF()
      SET(FAISS_OPT_LEVEL "${MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL}" CACHE STRING
          "Faiss CPU SIMD optimization level for MySQL source builds" FORCE)
      MESSAGE(STATUS "MySQL Vector Faiss SIMD opt level: ${FAISS_OPT_LEVEL}")

      IF(NOT TARGET faiss)
        ADD_SUBDIRECTORY("${MYSQL_VECTOR_FAISS_ROOT_HINTS}"
                         "${CMAKE_CURRENT_BINARY_DIR}/faiss" EXCLUDE_FROM_ALL)
      ENDIF()

      IF(TARGET faiss)
        SET(FAISS_TARGET faiss)
        SET(MYSQL_VECTOR_FAISS_TARGET_INCLUDE_ROOT
            "${MYSQL_VECTOR_FAISS_ROOT_HINTS}")
        IF(FAISS_OPT_LEVEL STREQUAL "avx2" AND TARGET faiss_avx2)
          SET(FAISS_TARGET faiss_avx2)
        ELSEIF(FAISS_OPT_LEVEL STREQUAL "avx512" AND TARGET faiss_avx512)
          SET(FAISS_TARGET faiss_avx512)
        ELSEIF(FAISS_OPT_LEVEL STREQUAL "avx512_spr" AND TARGET faiss_avx512_spr)
          SET(FAISS_TARGET faiss_avx512_spr)
        ELSEIF(FAISS_OPT_LEVEL STREQUAL "sve" AND TARGET faiss_sve)
          SET(FAISS_TARGET faiss_sve)
        ENDIF()
        FOREACH(MYSQL_VECTOR_FAISS_WARN_TARGET
                faiss faiss_avx2 faiss_avx512 faiss_avx512_spr faiss_sve)
          IF(TARGET ${MYSQL_VECTOR_FAISS_WARN_TARGET})
            TARGET_COMPILE_OPTIONS(${MYSQL_VECTOR_FAISS_WARN_TARGET} PRIVATE
                                   -Wno-error)
          ENDIF()
        ENDFOREACH()
      ENDIF()

      IF(MYSQL_VECTOR_FAISS_RESTORE_BUILD_TESTING)
        SET(BUILD_TESTING "${MYSQL_VECTOR_FAISS_SAVED_BUILD_TESTING}" CACHE BOOL
            "Restore MySQL BUILD_TESTING" FORCE)
      ELSE()
        UNSET(BUILD_TESTING CACHE)
      ENDIF()
    ENDIF()

    IF(NOT FAISS_TARGET AND
       (MYSQL_VECTOR_FAISS_ROOT_HINTS OR
        MYSQL_VECTOR_FAISS_INCLUDE_HINTS OR
        MYSQL_VECTOR_FAISS_LIBRARY_HINTS))
      FIND_PATH(FAISS_INCLUDE_DIR
        NAMES faiss/Index.h
        HINTS ${MYSQL_VECTOR_FAISS_INCLUDE_HINTS} ${MYSQL_VECTOR_FAISS_ROOT_HINTS}
        PATH_SUFFIXES include
        NO_DEFAULT_PATH)
      MYSQL_VECTOR_SET_FIND_LIBRARY_MODE(MYSQL_VECTOR_FAISS_STATIC)
      FIND_LIBRARY(FAISS_LIBRARY
        NAMES faiss libfaiss
        HINTS ${MYSQL_VECTOR_FAISS_LIBRARY_HINTS} ${MYSQL_VECTOR_FAISS_ROOT_HINTS}
        PATH_SUFFIXES lib
        NO_DEFAULT_PATH)
      MYSQL_VECTOR_RESTORE_FIND_LIBRARY_MODE()
    ENDIF()

    SET(MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES "")
    IF(NOT FAISS_TARGET AND FAISS_LIBRARY)
      FIND_PACKAGE(OpenMP)
      UNSET(MYSQL_VECTOR_OPENBLAS_LIBRARY CACHE)
      UNSET(MYSQL_VECTOR_OPENBLAS_LIBRARY)
      MYSQL_VECTOR_SET_FIND_LIBRARY_MODE(MYSQL_VECTOR_FAISS_STATIC)
      FIND_LIBRARY(MYSQL_VECTOR_OPENBLAS_LIBRARY
        NAMES openblas libopenblas
        PATHS
          /opt/homebrew/opt/openblas/lib
          /usr/lib
          /usr/local/lib
          /usr/lib/x86_64-linux-gnu
      )
      MYSQL_VECTOR_RESTORE_FIND_LIBRARY_MODE()
      IF(OpenMP_CXX_FOUND)
        LIST(APPEND MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES OpenMP::OpenMP_CXX)
      ENDIF()
      IF(MYSQL_VECTOR_OPENBLAS_LIBRARY)
        LIST(APPEND MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES
          ${MYSQL_VECTOR_OPENBLAS_LIBRARY})
      ELSE()
        FIND_PACKAGE(BLAS)
        FIND_PACKAGE(LAPACK)
        IF(LAPACK_FOUND)
          LIST(APPEND MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES ${LAPACK_LIBRARIES})
        ELSEIF(BLAS_FOUND)
          LIST(APPEND MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES ${BLAS_LIBRARIES})
        ENDIF()
      ENDIF()
    ENDIF()

    SET(HNSWLIB_TARGET "")
    IF(MYSQL_VECTOR_HNSWLIB_ROOT_HINTS AND
       EXISTS "${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}/CMakeLists.txt" AND
       EXISTS "${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}/hnswlib/hnswlib.h")
      IF(NOT TARGET hnswlib AND NOT TARGET hnswlib::hnswlib)
        ADD_SUBDIRECTORY("${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}"
                         "${CMAKE_CURRENT_BINARY_DIR}/hnswlib" EXCLUDE_FROM_ALL)
      ENDIF()
      IF(TARGET hnswlib::hnswlib)
        SET(HNSWLIB_TARGET hnswlib::hnswlib)
      ELSEIF(TARGET hnswlib)
        SET(HNSWLIB_TARGET hnswlib)
      ENDIF()
    ENDIF()

    IF(NOT HNSWLIB_TARGET AND
       (MYSQL_VECTOR_HNSWLIB_ROOT_HINTS OR MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS))
      FIND_PATH(HNSWLIB_INCLUDE_DIR
        NAMES hnswlib/hnswlib.h
        HINTS ${MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS} ${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}
        PATH_SUFFIXES include
        NO_DEFAULT_PATH
      )
    ENDIF()

    SET(MYSQL_VECTOR_DISKANN_OFFLINE_TARGET "")
    SET(MYSQL_VECTOR_DISKANN_VENDORED_TARGET "")
    SET(MYSQL_VECTOR_DISKANN_GARNET_TARGET "")
    SET(MYSQL_VECTOR_DISKANN_ADAPTER_SOURCE_DIR
        "${PROJECT_SOURCE_DIR}/extra/vector/diskann-offline-adapter-cpp")
    SET(MYSQL_VECTOR_DISKANN_VENDORED_SOURCE_DIR
        "${PROJECT_SOURCE_DIR}/extra/vector/diskann-vendored")
    SET(MYSQL_VECTOR_DISKANN_ROOT_KIND "")
    IF(MYSQL_VECTOR_DISKANN_ROOT_HINT)
      IF(EXISTS "${MYSQL_VECTOR_DISKANN_ROOT_HINT}/CMakeLists.txt" AND
         EXISTS "${MYSQL_VECTOR_DISKANN_ROOT_HINT}/include/pq_flash_index.h")
        SET(MYSQL_VECTOR_DISKANN_ROOT_KIND "cpp_main")
      ELSEIF(EXISTS "${MYSQL_VECTOR_DISKANN_ROOT_HINT}/Cargo.toml" AND
             EXISTS "${MYSQL_VECTOR_DISKANN_ROOT_HINT}/diskann-garnet/Cargo.toml")
        SET(MYSQL_VECTOR_DISKANN_ROOT_KIND "rust_garnet")
      ELSE()
        MESSAGE(FATAL_ERROR
          "MYSQL_VECTOR_DISKANN_ROOT must point to either the official "
          "DiskANN cpp_main C++ tree with CMakeLists.txt and "
          "include/pq_flash_index.h, or the official Rust workspace with "
          "Cargo.toml and diskann-garnet/Cargo.toml.")
      ENDIF()
      MESSAGE(STATUS
        "MySQL Vector DiskANN root kind: ${MYSQL_VECTOR_DISKANN_ROOT_KIND}")
    ENDIF()

    IF(MYSQL_VECTOR_DISKANN_ROOT_KIND STREQUAL "rust_garnet")
      FIND_PROGRAM(MYSQL_VECTOR_CARGO_EXECUTABLE cargo)
      IF(NOT MYSQL_VECTOR_CARGO_EXECUTABLE)
        MESSAGE(FATAL_ERROR
          "cargo is required to build DiskANN Garnet from "
          "MYSQL_VECTOR_DISKANN_ROOT=${MYSQL_VECTOR_DISKANN_ROOT_HINT}")
      ENDIF()
      SET(MYSQL_VECTOR_DISKANN_GARNET_TARGET_DIR
          "${CMAKE_BINARY_DIR}/diskann-garnet-target")
      SET(MYSQL_VECTOR_DISKANN_GARNET_LIB
          "${MYSQL_VECTOR_DISKANN_GARNET_TARGET_DIR}/release/${CMAKE_SHARED_LIBRARY_PREFIX}diskann_garnet${CMAKE_SHARED_LIBRARY_SUFFIX}")
      IF(NOT TARGET mysql_vector_diskann_garnet)
        ADD_CUSTOM_COMMAND(
          OUTPUT "${MYSQL_VECTOR_DISKANN_GARNET_LIB}"
          COMMAND ${CMAKE_COMMAND} -E env
                  "CARGO_TARGET_DIR=${MYSQL_VECTOR_DISKANN_GARNET_TARGET_DIR}"
                  "${MYSQL_VECTOR_CARGO_EXECUTABLE}" build
                  --manifest-path "${MYSQL_VECTOR_DISKANN_ROOT_HINT}/Cargo.toml"
                  -p diskann-garnet --release
          WORKING_DIRECTORY "${MYSQL_VECTOR_DISKANN_ROOT_HINT}"
          COMMENT "Building DiskANN Garnet from MYSQL_VECTOR_DISKANN_ROOT"
          VERBATIM)
        ADD_CUSTOM_TARGET(mysql_vector_diskann_garnet
          DEPENDS "${MYSQL_VECTOR_DISKANN_GARNET_LIB}")
      ENDIF()
      SET(MYSQL_VECTOR_DISKANN_GARNET_TARGET mysql_vector_diskann_garnet)
      SET(MYSQL_VECTOR_DISKANN_LIB_HINT
          "${MYSQL_VECTOR_DISKANN_GARNET_LIB}")
      SET(MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT
          "${MYSQL_VECTOR_DISKANN_GARNET_TARGET_DIR}/release")
    ENDIF()

    UNSET(MYSQL_VECTOR_DISKANN_NATIVE_LIBRARY_HINT CACHE)
    UNSET(MYSQL_VECTOR_DISKANN_NATIVE_LIBRARY_HINT)
    UNSET(MYSQL_VECTOR_DISKANN_GARNET_LIBRARY_HINT CACHE)
    UNSET(MYSQL_VECTOR_DISKANN_GARNET_LIBRARY_HINT)
    IF(MYSQL_VECTOR_DISKANN_LIB_DIR_HINT)
      MYSQL_VECTOR_SET_FIND_LIBRARY_MODE(MYSQL_VECTOR_DISKANN_STATIC)
      FIND_LIBRARY(MYSQL_VECTOR_DISKANN_NATIVE_LIBRARY_HINT
        NAMES diskann libdiskann
        HINTS ${MYSQL_VECTOR_DISKANN_LIB_DIR_HINT}
        NO_DEFAULT_PATH)
      FIND_LIBRARY(MYSQL_VECTOR_DISKANN_GARNET_LIBRARY_HINT
        NAMES diskann_garnet libdiskann_garnet
        HINTS ${MYSQL_VECTOR_DISKANN_LIB_DIR_HINT}
        NO_DEFAULT_PATH)
      MYSQL_VECTOR_RESTORE_FIND_LIBRARY_MODE()

      IF(MYSQL_VECTOR_DISKANN_NATIVE_LIBRARY_HINT)
        MESSAGE(STATUS
          "MySQL Vector DiskANN C++ library: "
          "${MYSQL_VECTOR_DISKANN_NATIVE_LIBRARY_HINT}")
        SET(MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT
            "${MYSQL_VECTOR_DISKANN_LIB_DIR_HINT}")
      ENDIF()
      IF(MYSQL_VECTOR_DISKANN_GARNET_LIBRARY_HINT)
        MESSAGE(STATUS
          "MySQL Vector DiskANN Garnet library: "
          "${MYSQL_VECTOR_DISKANN_GARNET_LIBRARY_HINT}")
        SET(MYSQL_VECTOR_DISKANN_LIB_HINT
            "${MYSQL_VECTOR_DISKANN_GARNET_LIBRARY_HINT}")
        SET(MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT
            "${MYSQL_VECTOR_DISKANN_LIB_DIR_HINT}")
      ENDIF()
    ENDIF()

    IF(EXISTS "${MYSQL_VECTOR_DISKANN_ADAPTER_SOURCE_DIR}/CMakeLists.txt" AND
       (MYSQL_VECTOR_DISKANN_ROOT_KIND STREQUAL "cpp_main" OR
        MYSQL_VECTOR_DISKANN_NATIVE_LIBRARY_HINT))
      IF(MYSQL_VECTOR_DISKANN_ROOT_KIND STREQUAL "cpp_main")
        SET(MYSQL_VECTOR_DISKANN_ROOT
            "${MYSQL_VECTOR_DISKANN_ROOT_HINT}" CACHE PATH
            "Root directory of the official DiskANN source tree" FORCE)
      ENDIF()
      IF(MYSQL_VECTOR_DISKANN_INCLUDE_HINTS)
        SET(MYSQL_VECTOR_DISKANN_INCLUDES
            "${MYSQL_VECTOR_DISKANN_INCLUDE_HINTS}" CACHE PATH
            "Directory containing official DiskANN C++ public headers" FORCE)
      ENDIF()
      IF(MYSQL_VECTOR_DISKANN_LIB_DIR_HINT)
        SET(MYSQL_VECTOR_DISKANN_LIB_DIR
            "${MYSQL_VECTOR_DISKANN_LIB_DIR_HINT}" CACHE PATH
            "Directory containing official DiskANN libraries" FORCE)
      ENDIF()
      SET(MYSQL_VECTOR_DISKANN_STATIC
          "${MYSQL_VECTOR_DISKANN_STATIC}" CACHE BOOL
          "Prefer static DiskANN libraries from MYSQL_VECTOR_DISKANN_LIB_DIR"
          FORCE)
      IF(NOT TARGET mysql_vector_diskann_offline_adapter)
        ADD_SUBDIRECTORY("${MYSQL_VECTOR_DISKANN_ADAPTER_SOURCE_DIR}"
                         "${CMAKE_BINARY_DIR}/mysql-vector-diskann-offline-adapter"
                         EXCLUDE_FROM_ALL)
      ENDIF()
      IF(TARGET mysql_vector_diskann_offline_adapter)
        SET(MYSQL_VECTOR_DISKANN_OFFLINE_TARGET
            mysql_vector_diskann_offline_adapter)
      ENDIF()
    ENDIF()

    IF(MYSQL_VECTOR_DISKANN_OFFLINE_TARGET AND
       EXISTS "${MYSQL_VECTOR_DISKANN_VENDORED_SOURCE_DIR}/CMakeLists.txt")
      IF(NOT TARGET mysql_vector_diskann_runtime)
        ADD_SUBDIRECTORY("${MYSQL_VECTOR_DISKANN_VENDORED_SOURCE_DIR}"
                         "${CMAKE_BINARY_DIR}/mysql-vector-diskann-vendored"
                         EXCLUDE_FROM_ALL)
      ENDIF()
      IF(TARGET mysql_vector_diskann_runtime)
        SET(MYSQL_VECTOR_DISKANN_VENDORED_TARGET
            mysql_vector_diskann_runtime)
      ENDIF()
    ENDIF()
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_LINK_DISKANN target)
  IF(MYSQL_VECTOR_DISKANN_OFFLINE_TARGET OR MYSQL_VECTOR_DISKANN_LIB_HINT OR
     MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT)
    TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_DISKANN=1)
  ENDIF()

  IF(MYSQL_VECTOR_DISKANN_OFFLINE_TARGET)
    IF(MYSQL_VECTOR_DISKANN_STATIC)
      TARGET_COMPILE_DEFINITIONS(
        ${target} PRIVATE MYSQL_VECTOR_DISKANN_OFFLINE_STATIC_LINKED=1)
      TARGET_LINK_LIBRARIES(${target}
        ${MYSQL_VECTOR_DISKANN_OFFLINE_TARGET})
    ELSE()
      ADD_DEPENDENCIES(${target} ${MYSQL_VECTOR_DISKANN_OFFLINE_TARGET})
      TARGET_COMPILE_DEFINITIONS(
        ${target} PRIVATE
        MYSQL_VECTOR_DISKANN_OFFLINE_DEFAULT_LIB="$<TARGET_FILE:${MYSQL_VECTOR_DISKANN_OFFLINE_TARGET}>")
    ENDIF()
  ENDIF()

  IF(MYSQL_VECTOR_DISKANN_VENDORED_TARGET)
    TARGET_COMPILE_DEFINITIONS(
      ${target} PRIVATE MYSQL_VECTOR_DISKANN_VENDORED_STATIC_LINKED=1)
    TARGET_LINK_LIBRARIES(${target} ${MYSQL_VECTOR_DISKANN_VENDORED_TARGET})
  ENDIF()

  IF(MYSQL_VECTOR_DISKANN_LIB_HINT)
    IF(MYSQL_VECTOR_DISKANN_GARNET_TARGET)
      ADD_DEPENDENCIES(${target} ${MYSQL_VECTOR_DISKANN_GARNET_TARGET})
    ENDIF()
    TARGET_COMPILE_DEFINITIONS(
      ${target} PRIVATE
      MYSQL_VECTOR_DISKANN_DEFAULT_LIB="${MYSQL_VECTOR_DISKANN_LIB_HINT}")
  ENDIF()

  IF(MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT)
    TARGET_COMPILE_DEFINITIONS(
      ${target} PRIVATE
      MYSQL_VECTOR_DISKANN_DEFAULT_LIB_DIR="${MYSQL_VECTOR_DISKANN_RUNTIME_LIB_DIR_HINT}")
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_LINK_BACKEND_TESTS target)
  IF(HAVE_VECTOR_INDEX)
    IF(FAISS_TARGET OR (FAISS_INCLUDE_DIR AND FAISS_LIBRARY))
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_FAISS=1)
      IF(FAISS_TARGET)
        IF(MYSQL_VECTOR_FAISS_TARGET_INCLUDE_ROOT)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
            ${MYSQL_VECTOR_FAISS_TARGET_INCLUDE_ROOT})
        ENDIF()
        IF(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
            ${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_TARGET})
      ELSE()
        FIND_PATH(LIBOMP_INCLUDE_DIR
          NAMES omp.h
          PATHS
            /opt/homebrew/opt/libomp/include
        )
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${FAISS_INCLUDE_DIR})
        IF(LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_LIBRARY}
          ${MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES})
      ENDIF()
    ENDIF()

    IF(HNSWLIB_TARGET OR HNSWLIB_INCLUDE_DIR)
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_HNSWLIB=1)
      IF(HNSWLIB_TARGET)
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
          ${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS})
        TARGET_LINK_LIBRARIES(${target} ${HNSWLIB_TARGET})
      ELSE()
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${HNSWLIB_INCLUDE_DIR})
      ENDIF()
    ENDIF()

    MYSQL_VECTOR_LINK_DISKANN(${target})
  ENDIF()
ENDMACRO()

# Link configured vector backends into a server target.
MACRO(MYSQL_VECTOR_LINK_BACKENDS target)
  IF(HAVE_VECTOR_INDEX)
    SET(MYSQL_VECTOR_HAS_FAISS_SOURCE FALSE)
    IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vector/vector_index_backend_faiss.cc")
      SET(MYSQL_VECTOR_HAS_FAISS_SOURCE TRUE)
    ENDIF()

    SET(MYSQL_VECTOR_HAS_HNSWLIB_SOURCE FALSE)
    IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vector/vector_index_backend_hnswlib.cc")
      SET(MYSQL_VECTOR_HAS_HNSWLIB_SOURCE TRUE)
    ENDIF()

    IF(MYSQL_VECTOR_HAS_FAISS_SOURCE AND
       (FAISS_TARGET OR (FAISS_INCLUDE_DIR AND FAISS_LIBRARY)))
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_FAISS=1)
      IF(FAISS_TARGET)
        IF(MYSQL_VECTOR_FAISS_TARGET_INCLUDE_ROOT)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
            ${MYSQL_VECTOR_FAISS_TARGET_INCLUDE_ROOT})
        ENDIF()
        IF(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
            ${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_TARGET})
      ELSE()
        FIND_PATH(LIBOMP_INCLUDE_DIR
          NAMES omp.h
          PATHS
            /opt/homebrew/opt/libomp/include
        )
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${FAISS_INCLUDE_DIR})
        IF(LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_LIBRARY}
          ${MYSQL_VECTOR_FAISS_EXTRA_LIBRARIES})
      ENDIF()
    ENDIF()

    IF(MYSQL_VECTOR_HAS_HNSWLIB_SOURCE AND
       (HNSWLIB_TARGET OR HNSWLIB_INCLUDE_DIR))
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_HNSWLIB=1)
      IF(HNSWLIB_TARGET)
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
          ${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS})
        TARGET_LINK_LIBRARIES(${target} ${HNSWLIB_TARGET})
      ELSE()
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${HNSWLIB_INCLUDE_DIR})
      ENDIF()
      IF(MYSQL_VECTOR_ENABLE_NATIVE_SIMD)
        INCLUDE(CheckCXXCompilerFlag)
        SET(MYSQL_VECTOR_NATIVE_SIMD_FLAG "")
        CHECK_CXX_COMPILER_FLAG("-march=native" MYSQL_VECTOR_HAS_MARCH_NATIVE)
        IF(MYSQL_VECTOR_HAS_MARCH_NATIVE)
          SET(MYSQL_VECTOR_NATIVE_SIMD_FLAG "-march=native")
        ELSE()
          CHECK_CXX_COMPILER_FLAG("-mcpu=native" MYSQL_VECTOR_HAS_MCPU_NATIVE)
          IF(MYSQL_VECTOR_HAS_MCPU_NATIVE)
            SET(MYSQL_VECTOR_NATIVE_SIMD_FLAG "-mcpu=native")
          ENDIF()
        ENDIF()
        IF(MYSQL_VECTOR_NATIVE_SIMD_FLAG)
          SET_PROPERTY(SOURCE
            vector/vector_index_backend_hnswlib.cc
            APPEND PROPERTY COMPILE_OPTIONS "${MYSQL_VECTOR_NATIVE_SIMD_FLAG}")
          TARGET_COMPILE_DEFINITIONS(${target} PRIVATE MYSQL_VECTOR_NATIVE_SIMD=1)
          MESSAGE(STATUS
            "MySQL Vector hnswlib native SIMD flag: "
            "${MYSQL_VECTOR_NATIVE_SIMD_FLAG}")
        ELSE()
          MESSAGE(STATUS
            "MySQL Vector native SIMD requested but no supported compiler flag was found")
        ENDIF()
      ENDIF()
    ENDIF()

    MYSQL_VECTOR_LINK_DISKANN(${target})

  ENDIF()
ENDMACRO()
