# Copyright (c) 2026, Oracle and/or its affiliates.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2.0,
# as published by the Free Software Foundation.

# Configure optional MySQL Vector native backend dependencies.
MACRO(MYSQL_VECTOR_CONFIGURE_BACKENDS)
  SET(FAISS_TARGET "")
  SET(HNSWLIB_TARGET "")

  IF(HAVE_VECTOR_INDEX)
    SET(MYSQL_VECTOR_FAISS_ROOT "" CACHE PATH
        "Root directory of the Faiss installation")
    SET(MYSQL_VECTOR_FAISS_INCLUDE_DIR "" CACHE PATH
        "Directory containing Faiss headers")
    SET(MYSQL_VECTOR_FAISS_LIBRARY_DIR "" CACHE PATH
        "Directory containing the Faiss library")
    SET(MYSQL_VECTOR_HNSWLIB_ROOT "" CACHE PATH
        "Root directory of the hnswlib installation")
    SET(MYSQL_VECTOR_HNSWLIB_INCLUDE_DIR "" CACHE PATH
        "Directory containing hnswlib headers")
    SET(MYSQL_VECTOR_DISKANN_LIB "" CACHE FILEPATH
        "Full path to the DiskANN shared library")
    SET(MYSQL_VECTOR_DISKANN_LIB_DIR "" CACHE PATH
        "Directory containing the DiskANN shared library")
    OPTION(MYSQL_VECTOR_ENABLE_NATIVE_SIMD
           "Compile native vector backends with CPU-native SIMD flags when available"
           ON)
    SET(MYSQL_VECTOR_FAISS_OPT_LEVEL "" CACHE STRING
        "Faiss source-build CPU SIMD optimization level; empty selects the MySQL default")
    SET_PROPERTY(CACHE MYSQL_VECTOR_FAISS_OPT_LEVEL PROPERTY STRINGS
                 "" generic dd avx2 avx512 avx512_spr sve)

    SET(MYSQL_VECTOR_FAISS_ROOT_HINTS "${MYSQL_VECTOR_FAISS_ROOT}")
    IF(NOT MYSQL_VECTOR_FAISS_ROOT_HINTS)
      SET(MYSQL_VECTOR_FAISS_ROOT_HINTS "$ENV{MYSQL_VECTOR_FAISS_ROOT}")
    ENDIF()

    SET(MYSQL_VECTOR_FAISS_INCLUDE_HINTS "${MYSQL_VECTOR_FAISS_INCLUDE_DIR}")
    IF(NOT MYSQL_VECTOR_FAISS_INCLUDE_HINTS)
      SET(MYSQL_VECTOR_FAISS_INCLUDE_HINTS "$ENV{MYSQL_VECTOR_FAISS_INCLUDE_DIR}")
    ENDIF()

    SET(MYSQL_VECTOR_FAISS_LIBRARY_HINTS "${MYSQL_VECTOR_FAISS_LIBRARY_DIR}")
    IF(NOT MYSQL_VECTOR_FAISS_LIBRARY_HINTS)
      SET(MYSQL_VECTOR_FAISS_LIBRARY_HINTS "$ENV{MYSQL_VECTOR_FAISS_LIBRARY_DIR}")
    ENDIF()

    SET(MYSQL_VECTOR_HNSWLIB_ROOT_HINTS "${MYSQL_VECTOR_HNSWLIB_ROOT}")
    IF(NOT MYSQL_VECTOR_HNSWLIB_ROOT_HINTS)
      SET(MYSQL_VECTOR_HNSWLIB_ROOT_HINTS "$ENV{MYSQL_VECTOR_HNSWLIB_ROOT}")
    ENDIF()

    SET(MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS "${MYSQL_VECTOR_HNSWLIB_INCLUDE_DIR}")
    IF(NOT MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS)
      SET(MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS "$ENV{MYSQL_VECTOR_HNSWLIB_INCLUDE_DIR}")
    ENDIF()

    SET(MYSQL_VECTOR_DISKANN_LIB_HINT "${MYSQL_VECTOR_DISKANN_LIB}")
    IF(NOT MYSQL_VECTOR_DISKANN_LIB_HINT)
      SET(MYSQL_VECTOR_DISKANN_LIB_HINT "$ENV{MYSQL_VECTOR_DISKANN_LIB}")
    ENDIF()

    SET(MYSQL_VECTOR_DISKANN_LIB_DIR_HINT "${MYSQL_VECTOR_DISKANN_LIB_DIR}")
    IF(NOT MYSQL_VECTOR_DISKANN_LIB_DIR_HINT)
      SET(MYSQL_VECTOR_DISKANN_LIB_DIR_HINT "$ENV{MYSQL_VECTOR_DISKANN_LIB_DIR}")
    ENDIF()

    IF(MYSQL_VECTOR_FAISS_ROOT_HINTS OR MYSQL_VECTOR_FAISS_INCLUDE_HINTS OR
       MYSQL_VECTOR_FAISS_LIBRARY_HINTS)
      UNSET(FAISS_INCLUDE_DIR CACHE)
      UNSET(FAISS_LIBRARY CACHE)
    ENDIF()

    IF(MYSQL_VECTOR_HNSWLIB_ROOT_HINTS OR MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS)
      UNSET(HNSWLIB_INCLUDE_DIR CACHE)
    ENDIF()

    SET(FAISS_TARGET "")
    IF(MYSQL_VECTOR_FAISS_ROOT_HINTS AND
       EXISTS "${MYSQL_VECTOR_FAISS_ROOT_HINTS}/CMakeLists.txt" AND
       EXISTS "${MYSQL_VECTOR_FAISS_ROOT_HINTS}/faiss/Index.h")
      IF(APPLE)
        FIND_PATH(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR
          NAMES omp.h
          PATHS
            /opt/homebrew/opt/libomp/include
        )
        FIND_LIBRARY(MYSQL_VECTOR_LIBOMP_LIBRARY
          NAMES omp libomp
          PATHS
            /opt/homebrew/opt/libomp/lib
        )
        IF(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR AND MYSQL_VECTOR_LIBOMP_LIBRARY)
          SET(OpenMP_C_FLAGS "-Xpreprocessor -fopenmp" CACHE STRING
              "OpenMP C flags for Faiss source builds" FORCE)
          SET(OpenMP_CXX_FLAGS "-Xpreprocessor -fopenmp" CACHE STRING
              "OpenMP CXX flags for Faiss source builds" FORCE)
          SET(OpenMP_C_INCLUDE_DIR "${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR}" CACHE PATH
              "OpenMP C include dir for Faiss source builds" FORCE)
          SET(OpenMP_CXX_INCLUDE_DIR "${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR}" CACHE PATH
              "OpenMP CXX include dir for Faiss source builds" FORCE)
          SET(OpenMP_C_LIB_NAMES "omp" CACHE STRING
              "OpenMP C libraries for Faiss source builds" FORCE)
          SET(OpenMP_CXX_LIB_NAMES "omp" CACHE STRING
              "OpenMP CXX libraries for Faiss source builds" FORCE)
          SET(OpenMP_omp_LIBRARY "${MYSQL_VECTOR_LIBOMP_LIBRARY}" CACHE FILEPATH
              "OpenMP runtime library for Faiss source builds" FORCE)
        ENDIF()
      ENDIF()

      SET(MYSQL_VECTOR_FAISS_SAVED_BUILD_TESTING "${BUILD_TESTING}")
      SET(MYSQL_VECTOR_FAISS_RESTORE_BUILD_TESTING FALSE)
      IF(DEFINED BUILD_TESTING)
        SET(MYSQL_VECTOR_FAISS_RESTORE_BUILD_TESTING TRUE)
      ENDIF()

      SET(BUILD_TESTING OFF CACHE BOOL "Disable Faiss tests in MySQL builds" FORCE)
      SET(FAISS_ENABLE_GPU OFF CACHE BOOL "Disable Faiss GPU support in MySQL builds" FORCE)
      SET(FAISS_ENABLE_CUVS OFF CACHE BOOL "Disable Faiss cuVS support in MySQL builds" FORCE)
      SET(FAISS_ENABLE_ROCM OFF CACHE BOOL "Disable Faiss ROCm support in MySQL builds" FORCE)
      SET(FAISS_ENABLE_MKL OFF CACHE BOOL "Disable Faiss MKL in MySQL builds" FORCE)
      SET(FAISS_ENABLE_PYTHON OFF CACHE BOOL "Disable Faiss Python bindings in MySQL builds" FORCE)
      SET(FAISS_ENABLE_C_API OFF CACHE BOOL "Disable Faiss C API in MySQL builds" FORCE)
      SET(FAISS_ENABLE_EXTRAS OFF CACHE BOOL "Disable Faiss demos and extras in MySQL builds" FORCE)
      SET(FAISS_ENABLE_SVS OFF CACHE BOOL "Disable Faiss SVS integration in MySQL builds" FORCE)
      SET(FAISS_USE_LTO OFF CACHE BOOL "Disable Faiss LTO in MySQL builds" FORCE)
      SET(MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL
          "${MYSQL_VECTOR_FAISS_OPT_LEVEL}")
      IF(NOT MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL)
        IF(MYSQL_VECTOR_ENABLE_NATIVE_SIMD AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
          SET(MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL "dd")
        ELSE()
          SET(MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL "generic")
        ENDIF()
      ENDIF()
      SET(FAISS_OPT_LEVEL "${MYSQL_VECTOR_SELECTED_FAISS_OPT_LEVEL}" CACHE STRING
          "Faiss CPU SIMD optimization level for MySQL source builds" FORCE)
      MESSAGE(STATUS "MySQL Vector Faiss SIMD opt level: ${FAISS_OPT_LEVEL}")

      IF(NOT TARGET faiss)
        ADD_SUBDIRECTORY("${MYSQL_VECTOR_FAISS_ROOT_HINTS}"
                         "${CMAKE_CURRENT_BINARY_DIR}/faiss" EXCLUDE_FROM_ALL)
      ENDIF()

      IF(TARGET faiss)
        SET(FAISS_TARGET faiss)
        IF(FAISS_OPT_LEVEL STREQUAL "avx2" AND TARGET faiss_avx2)
          SET(FAISS_TARGET faiss_avx2)
        ELSEIF(FAISS_OPT_LEVEL STREQUAL "avx512" AND TARGET faiss_avx512)
          SET(FAISS_TARGET faiss_avx512)
        ELSEIF(FAISS_OPT_LEVEL STREQUAL "avx512_spr" AND TARGET faiss_avx512_spr)
          SET(FAISS_TARGET faiss_avx512_spr)
        ELSEIF(FAISS_OPT_LEVEL STREQUAL "sve" AND TARGET faiss_sve)
          SET(FAISS_TARGET faiss_sve)
        ENDIF()
        FOREACH(MYSQL_VECTOR_FAISS_WARN_TARGET
                faiss faiss_avx2 faiss_avx512 faiss_avx512_spr faiss_sve)
          IF(TARGET ${MYSQL_VECTOR_FAISS_WARN_TARGET})
            TARGET_COMPILE_OPTIONS(${MYSQL_VECTOR_FAISS_WARN_TARGET} PRIVATE
                                   -Wno-error)
          ENDIF()
        ENDFOREACH()
      ENDIF()

      IF(MYSQL_VECTOR_FAISS_RESTORE_BUILD_TESTING)
        SET(BUILD_TESTING "${MYSQL_VECTOR_FAISS_SAVED_BUILD_TESTING}" CACHE BOOL
            "Restore MySQL BUILD_TESTING" FORCE)
      ELSE()
        UNSET(BUILD_TESTING CACHE)
      ENDIF()
    ENDIF()

    IF(NOT FAISS_TARGET)
      FIND_PATH(FAISS_INCLUDE_DIR
        NAMES faiss/Index.h
        HINTS ${MYSQL_VECTOR_FAISS_INCLUDE_HINTS} ${MYSQL_VECTOR_FAISS_ROOT_HINTS}
        PATH_SUFFIXES include)
      FIND_LIBRARY(FAISS_LIBRARY
        NAMES faiss libfaiss
        HINTS ${MYSQL_VECTOR_FAISS_LIBRARY_HINTS} ${MYSQL_VECTOR_FAISS_ROOT_HINTS}
        PATH_SUFFIXES lib)
    ENDIF()

    SET(HNSWLIB_TARGET "")
    IF(MYSQL_VECTOR_HNSWLIB_ROOT_HINTS AND
       EXISTS "${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}/CMakeLists.txt" AND
       EXISTS "${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}/hnswlib/hnswlib.h")
      IF(NOT TARGET hnswlib AND NOT TARGET hnswlib::hnswlib)
        ADD_SUBDIRECTORY("${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}"
                         "${CMAKE_CURRENT_BINARY_DIR}/hnswlib" EXCLUDE_FROM_ALL)
      ENDIF()
      IF(TARGET hnswlib::hnswlib)
        SET(HNSWLIB_TARGET hnswlib::hnswlib)
      ELSEIF(TARGET hnswlib)
        SET(HNSWLIB_TARGET hnswlib)
      ENDIF()
    ENDIF()

    IF(NOT HNSWLIB_TARGET)
      FIND_PATH(HNSWLIB_INCLUDE_DIR
        NAMES hnswlib/hnswlib.h
        HINTS ${MYSQL_VECTOR_HNSWLIB_INCLUDE_HINTS} ${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS}
        PATH_SUFFIXES include
      )
    ENDIF()
  ENDIF()
ENDMACRO()

MACRO(MYSQL_VECTOR_LINK_BACKEND_TESTS target)
  IF(HAVE_VECTOR_INDEX)
    IF(FAISS_TARGET OR (FAISS_INCLUDE_DIR AND FAISS_LIBRARY))
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_FAISS=1)
      IF(FAISS_TARGET)
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
          ${MYSQL_VECTOR_FAISS_ROOT_HINTS})
        IF(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
            ${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_TARGET})
      ELSE()
        FIND_PATH(LIBOMP_INCLUDE_DIR
          NAMES omp.h
          PATHS
            /opt/homebrew/opt/libomp/include
        )
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${FAISS_INCLUDE_DIR})
        IF(LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_LIBRARY})
      ENDIF()
    ENDIF()

    IF(HNSWLIB_TARGET OR HNSWLIB_INCLUDE_DIR)
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_HNSWLIB=1)
      IF(HNSWLIB_TARGET)
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
          ${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS})
        TARGET_LINK_LIBRARIES(${target} ${HNSWLIB_TARGET})
      ELSE()
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${HNSWLIB_INCLUDE_DIR})
      ENDIF()
    ENDIF()
  ENDIF()
ENDMACRO()

# Link configured vector backends into a server target.
MACRO(MYSQL_VECTOR_LINK_BACKENDS target)
  IF(HAVE_VECTOR_INDEX)
    SET(MYSQL_VECTOR_HAS_FAISS_SOURCE FALSE)
    IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vector/vector_index_backend_faiss.cc")
      SET(MYSQL_VECTOR_HAS_FAISS_SOURCE TRUE)
    ENDIF()

    SET(MYSQL_VECTOR_HAS_HNSWLIB_SOURCE FALSE)
    IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vector/vector_index_backend_hnswlib.cc")
      SET(MYSQL_VECTOR_HAS_HNSWLIB_SOURCE TRUE)
    ENDIF()

    IF(MYSQL_VECTOR_HAS_FAISS_SOURCE AND
       (FAISS_TARGET OR (FAISS_INCLUDE_DIR AND FAISS_LIBRARY)))
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_FAISS=1)
      IF(FAISS_TARGET)
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
          ${MYSQL_VECTOR_FAISS_ROOT_HINTS})
        IF(MYSQL_VECTOR_LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
            ${MYSQL_VECTOR_LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_TARGET})
      ELSE()
        FIND_PATH(LIBOMP_INCLUDE_DIR
          NAMES omp.h
          PATHS
            /opt/homebrew/opt/libomp/include
        )
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${FAISS_INCLUDE_DIR})
        IF(LIBOMP_INCLUDE_DIR)
          TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${LIBOMP_INCLUDE_DIR})
        ENDIF()
        TARGET_LINK_LIBRARIES(${target} ${FAISS_LIBRARY})
      ENDIF()
    ENDIF()

    IF(MYSQL_VECTOR_HAS_HNSWLIB_SOURCE AND
       (HNSWLIB_TARGET OR HNSWLIB_INCLUDE_DIR))
      TARGET_COMPILE_DEFINITIONS(${target} PRIVATE HAVE_HNSWLIB=1)
      IF(HNSWLIB_TARGET)
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE
          ${MYSQL_VECTOR_HNSWLIB_ROOT_HINTS})
        TARGET_LINK_LIBRARIES(${target} ${HNSWLIB_TARGET})
      ELSE()
        TARGET_INCLUDE_DIRECTORIES(${target} SYSTEM PRIVATE ${HNSWLIB_INCLUDE_DIR})
      ENDIF()
      IF(MYSQL_VECTOR_ENABLE_NATIVE_SIMD)
        INCLUDE(CheckCXXCompilerFlag)
        SET(MYSQL_VECTOR_NATIVE_SIMD_FLAG "")
        CHECK_CXX_COMPILER_FLAG("-march=native" MYSQL_VECTOR_HAS_MARCH_NATIVE)
        IF(MYSQL_VECTOR_HAS_MARCH_NATIVE)
          SET(MYSQL_VECTOR_NATIVE_SIMD_FLAG "-march=native")
        ELSE()
          CHECK_CXX_COMPILER_FLAG("-mcpu=native" MYSQL_VECTOR_HAS_MCPU_NATIVE)
          IF(MYSQL_VECTOR_HAS_MCPU_NATIVE)
            SET(MYSQL_VECTOR_NATIVE_SIMD_FLAG "-mcpu=native")
          ENDIF()
        ENDIF()
        IF(MYSQL_VECTOR_NATIVE_SIMD_FLAG)
          SET_PROPERTY(SOURCE
            vector/vector_index_backend_hnswlib.cc
            APPEND PROPERTY COMPILE_OPTIONS "${MYSQL_VECTOR_NATIVE_SIMD_FLAG}")
          TARGET_COMPILE_DEFINITIONS(${target} PRIVATE MYSQL_VECTOR_NATIVE_SIMD=1)
          MESSAGE(STATUS
            "MySQL Vector hnswlib native SIMD flag: "
            "${MYSQL_VECTOR_NATIVE_SIMD_FLAG}")
        ELSE()
          MESSAGE(STATUS
            "MySQL Vector native SIMD requested but no supported compiler flag was found")
        ENDIF()
      ENDIF()
    ENDIF()

    IF(MYSQL_VECTOR_DISKANN_LIB_HINT)
      TARGET_COMPILE_DEFINITIONS(
        ${target} PRIVATE
        MYSQL_VECTOR_DISKANN_DEFAULT_LIB="${MYSQL_VECTOR_DISKANN_LIB_HINT}")
    ENDIF()

    IF(MYSQL_VECTOR_DISKANN_LIB_DIR_HINT)
      TARGET_COMPILE_DEFINITIONS(
        ${target} PRIVATE
        MYSQL_VECTOR_DISKANN_DEFAULT_LIB_DIR="${MYSQL_VECTOR_DISKANN_LIB_DIR_HINT}")
    ENDIF()
  ENDIF()
ENDMACRO()
